#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2016, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE="root@$1"
SERVICE=volapi

if [[ -z "$VOLAPI_ZONE" ]]; then
    VOLAPI_ZONE=$(ssh $NODE "vmadm lookup -1 alias=volapi0" 2>/dev/null)
fi
echo "VOLAPI_ZONE: $VOLAPI_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$VOLAPI_ZONE/root/opt/smartdc/${SERVICE}/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$VOLAPI_ZONE/root/opt/smartdc/${SERVICE}/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /config.json \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /tools/ \
    --exclude /tmp/

state=$(ssh ${NODE} svcs -z ${VOLAPI_ZONE} -H -o state ${SERVICE})
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${VOLAPI_ZONE} clear ${SERVICE}
else
    ssh ${NODE} svcadm -z ${VOLAPI_ZONE} restart ${SERVICE}
fi
